# Generated by Django 2.0 on 2018-09-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180928_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasheet',
            old_name='descriptions',
            new_name='description',
        ),
    ]
