# Generated by Django 2.0 on 2018-09-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180928_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='professions',
            new_name='profession',
        ),
    ]
